language: minimal

services:
  - docker

env:
  global:
    - SX_VER=v1.4.67
  jobs:
    - ES_VER=1.7.6-alpine
    - ES_VER=7.9.3

before_install:
  - docker network create lol
  - docker pull spectx/spectx:$SX_VER
  - >-
      docker run -d
      --name sx
      --network lol
      -p 18388:8388
      -e SPECTX_ACCEPT_EULA=true
      -e SPECTX_ADMIN_PASSWORD=kalamaja
      -v $(realpath spectx.lic):/opt/spectx/spectx.lic
      spectx/spectx:$SX_VER -vvv
  - docker exec -uroot sx bash '-c' 'while true ; do nc -zvn 127.0.0.1 8388 && break; sleep 0.1 ; done'
  - sleep 1
  - docker exec -uroot sx bash '-c' 'apk add sqlite; until [ -f /opt/spectxhome/sxwgui.db ] ; do echo . ; sleep 0.1 ; done; echo yep ; sqlite3 -cmd ".timeout 10000" /opt/spectxhome/sxwgui.db "update users set api_access_key = \"7a499b39279cb2f7\";" ; sqlite3 -cmd ".timeout 10000" /opt/spectxhome/sxwgui.db "select * from users;"'

  - docker pull elasticsearch:$ES_VER
  - >-
      docker run -d
      --name es
      --network lol
      -e discovery.type=single-node
      -e xpack.ml.enabled=false
      elasticsearch:$ES_VER
  - docker exec es bash '-c' 'while true ; do nc -zvn 127.0.0.1 9200 && break; sleep 0.1 ; done'

script:
  - >-
    for t in *.sx; do
      echo $t:
      { code=$(curl -s -o /dev/stderr --write-out "%{http_code}" -H'Authorization: Bearer 7a499b39279cb2f7' --data-binary @$t 'http://127.0.0.1:18388/API/v1.0/?scriptPath=/user'); } 2>&1
      if [ $((code/100)) -ne 2 ]; then exit $code; fi
    ; done

after_failure:
  - docker logs sx